{
  "openapi": "3.0.1",
  "servers": [
    {
      "description": "API de Movimentações Contábeis",
      "url": "{{host}}/api/ctb/v1/AccountingTransactions",
      "variables": {
        "serverUrl": {
          "default": "localhost"
        },
        "serverHttpPort": {
          "default": "8051"
        }
      }
    }
  ],
  "info": {
    "description": "API no módulo Contábil para consulta de movimentação de contas contábeis.",
    "version": "1.000",
    "title": "API de Movimentações Contábeis",
    "contact": {
      "name": "T-Talk",
      "url": "api.totvs.com.br",
      "email": "comiteintegracao@totvs.com.br"
    },
    "x-totvs": {
      "messageDocumentation": {
        "name": "AccountingTransactions",
        "description": "Listagem de Contas de Movimentações Contábeis.",
        "segment": "Contábil"
      },
      "productInformation": [
        {
          "product": "RM",
          "contact": "",
          "description": "Contas Contábeis e seus movimentos de Débito e Crédito.",
          "adapter": "",
          "helpUrl": ""
        }
      ]
    }
  },
  "paths": {
    "/AccountingTransactions": {
      "get": {
        "tags": [
          "AccountingTransactions"
        ],
        "summary": "Retorna uma lista de Movimentação Contábil.",
        "description": "Retorna uma lista de movimentação em Contas Contábeis.",
        "operationId": "GetAll",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo está disponível com todos os parâmetros.",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Order"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Page"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/PageSize"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Fields"
          },
          {
            "name": "companyId",
            "in": "query",
            "description": "Identificador da empresa",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "date",
            "in": "query",
            "description": "Equivalente ao Período Contábil (data inicial e data final)",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "currency",
            "in": "query",
            "description": "Moeda",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "account",
            "in": "query",
            "description": "Conta",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "branchId",
            "in": "query",
            "description": "Filial",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "costCenterCode",
            "in": "query",
            "description": "Código Centro de Custo",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de Movimentação foi obtida com sucesso.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": [
                        {
                          "companyId": 1,
                          "branchId": 1,
                          "account": "0.1.1",
                          "currency": "R$",
                          "date": "2009-12-31T00:00:00",
                          "value": -194609.77,
                          "creditValue": 0,
                          "debitValue": 0,
                          "costCenterCode": "01.1",
                          "natureAccount": "Credora"
                        },
                        {
                          "companyId": 1,
                          "branchId": 1,
                          "account": "0.1.2",
                          "currency": "R$",
                          "date": "2009-12-31T00:00:00",
                          "value": 194609.77,
                          "creditValue": 0,
                          "debitValue": 0,
                          "costCenterCode": "01.1",
                          "natureAccount": "Devedora"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Erro no momento da recuperação dos registros.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": []
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "São obrigatórios  filtros para codColigada (companyId) e Periodo de Movimentação Contábil (date), informe-os e tente novamente.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "Code": null,
                      "Message": "São obrigatórios filtros para codColigada (companyId) e Data de depreciação, pondendo  a Data ser passada em um período ($filter=date ge 'yyyy-mm-dd' and date le 'yyyy-mm-dd' ), informe-os e tente novamente.",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/AccountingTransactions/account": {
      "get": {
        "tags": [
          "AccountingTransactions/account"
        ],
        "summary": "Retorna movimentação de uma Conta específica dentro do período.",
        "description": "Retorna um único registro com a movimentação de acordo com a Conta, período e moeda informada.",
        "operationId": "GetOne",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo está disponível com todos os parâmetros.",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          },
          {
            "name": "companyId",
            "in": "query",
            "description": "Identificador da empresa",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "date",
            "in": "query",
            "description": "Data é período",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "currency",
            "in": "query",
            "description": "Moeda",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "account",
            "in": "query",
            "description": "Conta",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "branchId",
            "in": "query",
            "description": "Filial",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de Movimentação foi obtida com sucesso.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": {
                        "companyId": 1,
                        "branchId": 1,
                        "account": "0.1.1",
                        "currency": "R$",
                        "date": "2009-12-31T00:00:00",
                        "value": -194609.77,
                        "creditValue": 0,
                        "debitValue": 0,
                        "costCenterCode": "01.1",
                        "natureAccount": "Credora"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Erro no momento da recuperação dos registros.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": []
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Lista com todos os erros possiveis: Chave Incorreta! Campos necessários. CompanyId|date|account|currency",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo-1": {
                    "value": {
                      "Code": null,
                      "Message": "São obrigatórios filtros para codColigada (companyId) e Data de depreciação, pondendo  a Data ser passada em um período ($filter=date ge 'yyyy-mm-dd' and date le 'yyyy-mm-dd' ), informe-os e tente novamente.",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  },
                  "exemplo-2": {
                    "value": {
                      "Code": null,
                      "Message": "Favor preencha o filtro currency (Moeda), com uma Moeda válida.",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  },
                  "exemplo-3": {
                    "value": {
                      "Code": null,
                      "Message": "Favor preencha o filtro account (Conta), com uma conta válida.",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  },
                  "exemplo-4": {
                    "value": {
                      "Code": null,
                      "Message": "Favor preencha o filtro costCenterCode (Centro de Custo), com um Centro de Custo válido.",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/NotImplemented": {
      "post": {
        "tags": [
          "notImplemented"
        ],
        "summary": "Método POST não implementado. Essa API é exclusiva para consulta",
        "description": "Método POST não implementado. Essa API é exclusiva para consulta",
        "operationId": "Post",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": false,
              "note": "Este verbo não está implementado pois essa API é exclusiva para consultas.",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          }
        ],
        "responses": {
          "405": {
            "description": "Método POST não implementado. Essa API é exclusiva para consulta"
          }
        }
      },
      "put": {
        "tags": [
          "notImplemented"
        ],
        "summary": "Método PUT não implementado. Essa API é exclusiva para consulta",
        "description": "Método PUT não implementado. Essa API é exclusiva para consulta",
        "operationId": "Put",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": false,
              "note": "Este verbo não está implementado pois essa API é exclusiva para consultas.",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          }
        ],
        "responses": {
          "405": {
            "description": "Método PUT não implementado. Essa API é exclusiva para consulta"
          }
        }
      },
      "delete": {
        "tags": [
          "notImplemented"
        ],
        "summary": "Método DELETE não implementado. Essa API é exclusiva para consulta",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": false,
              "note": "Este verbo não está implementado pois essa API é exclusiva para consultas.",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "description": "Método PUT não implementado. Essa API é exclusiva para consulta",
        "operationId": "Delete",
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          }
        ],
        "responses": {
          "405": {
            "description": "Método DELETE não implementado. Essa API é exclusiva para consulta"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {},
    "schemas": {}
  }
}