{
  "openapi": "3.0.1",
  "servers": [
    {
      "description": "API de Depreciação Patrimonial",
      "url": "{{host}}/api/pat/v1/PatrimonyDepreciation",
      "variables": {
        "serverUrl": {
          "default": "localhost"
        },
        "serverHttpPort": {
          "default": "8051"
        }
      }
    }
  ],
  "info": {
    "description": "API para consulta de Patrimônios depreciados oriundos do Cálculo razão",
    "version": "1.000",
    "title": "Itens de Depreciação Patrimonial",
    "contact": {
      "name": "T-Talk",
      "url": "api.totvs.com.br",
      "email": "comiteintegracao@totvs.com.br"
    },
    "x-totvs": {
      "messageDocumentation": {
        "name": "PatrimonyDepreciation",
        "description": "Listagem de itens de depreciação patrimonial",
        "segment": "Patrimônio"
      },
      "productInformation": [
        {
          "product": "RM",
          "contact": "",
          "description": "Itens de descrição de patrimônios com seus valores e sua depreciação acumulada e atual",
          "adapter": "",
          "helpUrl": ""
        }
      ]
    }
  },
  "paths": {
    "/PatrimonyDepreciation": {
      "get": {
        "tags": [
          "PatrimonyDepreciation"
        ],
        "summary": "Listagem de registros de patrimônio e respectiva depreciação",
        "description": "Retorna uma lista de registros de patrimônios e detalhes de sua depreciação",
        "operationId": "GetAll",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo está disponível com todos os parâmetros",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Order"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Page"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/PageSize"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Fields"
          },
          {
            "name": "companyId",
            "in": "query",
            "description": "Identificador da empresa",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "date",
            "in": "query",
            "description": "Data da depreciação",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de Depreciação de Patrimônios foi obtida com sucesso",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": [
                        {
                          "id": "1|7|4|2012-04-30",
                          "companyId": 1,
                          "patrimonyId": 6,
                          "patrimonyCode": "01.01.0004",
                          "patrimonyDescription": "ALTERADO",
                          "calculationScenarioId": 1,
                          "descriptionScenario": "Cenário de cálculo padrão",
                          "periodDepreciationRate": 1.6666,
                          "accumulatedDepreciationRate": 100,
                          "indexCurrency": "R$",
                          "correctedBaseValue": 99.51,
                          "ajustedDepreciation": 0,
                          "correctedAcumuletedDepreciation": 99.51,
                          "residualBalance": 0,
                          "costCenterCode": "01.4",
                          "branchId": 1,
                          "departamentCode": "03",
                          "patrimonyCaloculationId": 7,
                          "date": "2012-04-30T00:00:00",
                          "reasonCalculationId": 4
                        },
                        {
                          "id": "1|7|5|2012-05-31",
                          "companyId": 1,
                          "patrimonyId": 6,
                          "patrimonyCode": "01.01.0004",
                          "patrimonyDescription": "ALTERADO",
                          "calculationScenarioId": 1,
                          "descriptionScenario": "Cenário de cálculo padrão",
                          "periodDepreciationRate": 1.6666,
                          "accumulatedDepreciationRate": 100,
                          "indexCurrency": "R$",
                          "correctedBaseValue": 99.51,
                          "ajustedDepreciation": 0,
                          "correctedAcumuletedDepreciation": 99.51,
                          "residualBalance": 0,
                          "costCenterCode": "01.4",
                          "branchId": 1,
                          "departamentCode": "03",
                          "patrimonyCaloculationId": 7,
                          "date": "2012-05-31T00:00:00",
                          "reasonCalculationId": 5
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Erro no momento da recuperação dos registros.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": []
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "São obrigatórios  filtros para codColigada (companyId) e Data de depreciação (date), informe-os e tente novamente.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "Code": null,
                      "Message": "São obrigatórios filtros para codColigada (companyId) e Data de depreciação, pondendo  a Data ser passada em um período ($filter=date ge 'yyyy-mm-dd' and date le 'yyyy-mm-dd' ), informe-os e tente novamente.",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "notImplemented"
        ],
        "summary": "Método POST não implementado. Essa API é exclusiva para consulta",
        "description": "Método POST não implementado. Essa API é exclusiva para consulta",
        "operationId": "Post",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": false,
              "note": "Este verbo não está implementado pois essa API é exclusiva para consulta",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          }
        ],
        "responses": {
          "405": {
            "description": "Método POST não implementado. Essa API é exclusiva para consulta"
          }
        }
      }
    },
    "/PatrimonyDepreciation/{id}": {
      "get": {
        "tags": [
          "PatrimonyDepreciation"
        ],
        "summary": "Recupera um item de depreciação patrimonial",
        "description": "Recupera um item de depreciação patrimonial",
        "operationId": "GetOne",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo está disponível com todos os parâmetros.",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Expand"
          },
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Fields"
          },
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "responses": {
          "200": {
            "description": "Registro recuperado com sucesso",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "id": "1|7|4|2012-04-30",
                      "companyId": 1,
                      "patrimonyId": 6,
                      "patrimonyCode": "01.01.0004",
                      "patrimonyDescription": "ALTERADO",
                      "calculationScenarioId": 1,
                      "descriptionScenario": "Cenário de cálculo padrão",
                      "periodDepreciationRate": 1.6666,
                      "accumulatedDepreciationRate": 100,
                      "indexCurrency": "R$",
                      "correctedBaseValue": 99.51,
                      "ajustedDepreciation": 0,
                      "correctedAcumuletedDepreciation": 99.51,
                      "residualBalance": 0,
                      "costCenterCode": "01.4",
                      "branchId": 1,
                      "departamentCode": "03",
                      "patrimonyCaloculationId": 7,
                      "date": "2012-04-30T00:00:00",
                      "reasonCalculationId": 4
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Erro no momento da recuperação dos registros.",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "hasNext": false,
                      "items": []
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Chave Incorreta! Campos necessários. CompanyId|patrimonyCalculationId|reasonCalculationId|date",
            "content": {
              "application/json": {
                "examples": {
                  "exemplo": {
                    "value": {
                      "Code": null,
                      "Message": "Chave incorreta! Campos necessários: companyId|patrimonyCalculationId|reasonCalculationId|date",
                      "DetailMessage": null,
                      "HelpUrl": null,
                      "Details": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "notImplemented"
        ],
        "summary": "Método PUT não implementado. Essa API é exclusiva para consulta",
        "description": "Método PUT não implementado. Essa API é exclusiva para consulta",
        "operationId": "Put",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": false,
              "note": "Este verbo não está implementado pois essa API é exclusiva para consulta",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          },
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "responses": {
          "405": {
            "description": "Método PUT não implementado. Essa API é exclusiva para consulta"
          }
        }
      },
      "delete": {
        "tags": [
          "notImplemented"
        ],
        "summary": "Método DELETE não implementado. Essa API é exclusiva para consulta",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": false,
              "note": "Este verbo não está implementado pois essa API é exclusiva para consulta",
              "minimalVersion": "12.1.35"
            }
          ]
        },
        "description": "Método PUT não implementado. Essa API é exclusiva para consulta",
        "operationId": "Delete",
        "parameters": [
          {
            "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization"
          },
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "responses": {
          "405": {
            "description": "Método DELETE não implementado. Essa API é exclusiva para consulta"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "id": {
        "name": "id",
        "in": "path",
        "description": "A chave {id} é composta da concatenação de 4 itens, sendo eles - CompanyId|patrimonyCalculationId|reasonCalculationId|date",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    },
    "schemas": {}
  }
}